name: DevSecOps Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake Build & Test
        run: |
          echo "✅ Build successful"
          echo "✅ Tests passed"

  sast-sca:
    name: SAST & SCA Scan
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake SAST Scan
        run: echo "✅ SAST scan completed (no critical vulnerabilities found)"

      - name: Fake SCA Scan
        run: echo "✅ SCA scan completed (no high severity vulnerabilities found)"

  dast:
    name: DAST Scan
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake DAST Scan
        run: echo "✅ DAST scan completed (no critical issues detected)"
